# https://taskfile.dev

version: "3"

tasks:
  format:py:
    cmds:
      - ruff format build.py
    sources:
      - build.py
    internal: true

  format:cs:
    cmds:
      - dotnet format EvanMod.csproj
    sources:
      - ./**/**.cs
    internal: true

  format:
    deps: [format:py, format:cs]

  format:check:py:
    cmds:
      - ruff format --check build.py
    sources:
      - build.py
    internal: true

  format:check:cs:
    cmds:
      - dotnet format EvanMod.csproj --verify-no-changes
    sources:
      - ./**/**.cs
    internal: true

  format:check:
    deps: [format:check:py, format:check:cs]

  build:py:
    cmds:
      - py build.py
    sources:
      - tmod.json
    internal: true

  build:cs:
    cmds:
      - dotnet build
    sources:
      - ./*/**.cs
      - ./*/**.png
      - ./*/**.hjson
      - ./build.txt
    internal: true

  build:
    deps: [build:py, build:cs]

  tag:
    cmds:
      - py build.py tag {{.CLI_ARGS}}
